### ISSUE TITLE
Improve and release 1.0.0?

### ISSUE THREAD

**Issue by dpc** [arcnmx/result-rs#1]
https://users.rust-lang.org/t/convenience-method-for-flipping-option-result-to-result-option/13695/17

**Comment by arcnmx** [comment]
Could you elaborate on what you mean by "improve"? Certainly I can bump the version number, it just hasn't seen changes in a while because it pretty much works as-is.

**Comment by dpc** [comment]
The version is the main one. We could discuss the naming as well. Eg. I was thinking about potentially implementing it for iterators etc. Let's discuss in the forum thread. There are more people there.

**Comment by arcnmx** [comment]
If you feel like any particular features are missing, feel free to open other issues detailing them!
